/*
Polar Backend SDK Server

Backend SDK API for polar

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polar

import (
	"encoding/json"
)

// checks if the ResponsesSdkLinkResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesSdkLinkResponseData{}

// ResponsesSdkLinkResponseData struct for ResponsesSdkLinkResponseData
type ResponsesSdkLinkResponseData struct {
	SdkLinkData *ResponsesSdkLink `json:"sdkLinkData,omitempty"`
}

// NewResponsesSdkLinkResponseData instantiates a new ResponsesSdkLinkResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesSdkLinkResponseData() *ResponsesSdkLinkResponseData {
	this := ResponsesSdkLinkResponseData{}
	return &this
}

// NewResponsesSdkLinkResponseDataWithDefaults instantiates a new ResponsesSdkLinkResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesSdkLinkResponseDataWithDefaults() *ResponsesSdkLinkResponseData {
	this := ResponsesSdkLinkResponseData{}
	return &this
}

// GetSdkLinkData returns the SdkLinkData field value if set, zero value otherwise.
func (o *ResponsesSdkLinkResponseData) GetSdkLinkData() ResponsesSdkLink {
	if o == nil || IsNil(o.SdkLinkData) {
		var ret ResponsesSdkLink
		return ret
	}
	return *o.SdkLinkData
}

// GetSdkLinkDataOk returns a tuple with the SdkLinkData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesSdkLinkResponseData) GetSdkLinkDataOk() (*ResponsesSdkLink, bool) {
	if o == nil || IsNil(o.SdkLinkData) {
		return nil, false
	}
	return o.SdkLinkData, true
}

// HasSdkLinkData returns a boolean if a field has been set.
func (o *ResponsesSdkLinkResponseData) HasSdkLinkData() bool {
	if o != nil && !IsNil(o.SdkLinkData) {
		return true
	}

	return false
}

// SetSdkLinkData gets a reference to the given ResponsesSdkLink and assigns it to the SdkLinkData field.
func (o *ResponsesSdkLinkResponseData) SetSdkLinkData(v ResponsesSdkLink) {
	o.SdkLinkData = &v
}

func (o ResponsesSdkLinkResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesSdkLinkResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SdkLinkData) {
		toSerialize["sdkLinkData"] = o.SdkLinkData
	}
	return toSerialize, nil
}

type NullableResponsesSdkLinkResponseData struct {
	value *ResponsesSdkLinkResponseData
	isSet bool
}

func (v NullableResponsesSdkLinkResponseData) Get() *ResponsesSdkLinkResponseData {
	return v.value
}

func (v *NullableResponsesSdkLinkResponseData) Set(val *ResponsesSdkLinkResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesSdkLinkResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesSdkLinkResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesSdkLinkResponseData(val *ResponsesSdkLinkResponseData) *NullableResponsesSdkLinkResponseData {
	return &NullableResponsesSdkLinkResponseData{value: val, isSet: true}
}

func (v NullableResponsesSdkLinkResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesSdkLinkResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


