/*
Polar Backend SDK Server

Backend SDK API for polar

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polar

import (
	"encoding/json"
)

// checks if the RequestsLinkAnalyticTags type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestsLinkAnalyticTags{}

// RequestsLinkAnalyticTags struct for RequestsLinkAnalyticTags
type RequestsLinkAnalyticTags struct {
	Campaign NullableString `json:"campaign,omitempty"`
	Channel NullableString `json:"channel,omitempty"`
	Feature NullableString `json:"feature,omitempty"`
	Tags NullableString `json:"tags,omitempty"`
}

// NewRequestsLinkAnalyticTags instantiates a new RequestsLinkAnalyticTags object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestsLinkAnalyticTags() *RequestsLinkAnalyticTags {
	this := RequestsLinkAnalyticTags{}
	return &this
}

// NewRequestsLinkAnalyticTagsWithDefaults instantiates a new RequestsLinkAnalyticTags object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestsLinkAnalyticTagsWithDefaults() *RequestsLinkAnalyticTags {
	this := RequestsLinkAnalyticTags{}
	return &this
}

// GetCampaign returns the Campaign field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RequestsLinkAnalyticTags) GetCampaign() string {
	if o == nil || IsNil(o.Campaign.Get()) {
		var ret string
		return ret
	}
	return *o.Campaign.Get()
}

// GetCampaignOk returns a tuple with the Campaign field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RequestsLinkAnalyticTags) GetCampaignOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Campaign.Get(), o.Campaign.IsSet()
}

// HasCampaign returns a boolean if a field has been set.
func (o *RequestsLinkAnalyticTags) HasCampaign() bool {
	if o != nil && o.Campaign.IsSet() {
		return true
	}

	return false
}

// SetCampaign gets a reference to the given NullableString and assigns it to the Campaign field.
func (o *RequestsLinkAnalyticTags) SetCampaign(v string) {
	o.Campaign.Set(&v)
}
// SetCampaignNil sets the value for Campaign to be an explicit nil
func (o *RequestsLinkAnalyticTags) SetCampaignNil() {
	o.Campaign.Set(nil)
}

// UnsetCampaign ensures that no value is present for Campaign, not even an explicit nil
func (o *RequestsLinkAnalyticTags) UnsetCampaign() {
	o.Campaign.Unset()
}

// GetChannel returns the Channel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RequestsLinkAnalyticTags) GetChannel() string {
	if o == nil || IsNil(o.Channel.Get()) {
		var ret string
		return ret
	}
	return *o.Channel.Get()
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RequestsLinkAnalyticTags) GetChannelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Channel.Get(), o.Channel.IsSet()
}

// HasChannel returns a boolean if a field has been set.
func (o *RequestsLinkAnalyticTags) HasChannel() bool {
	if o != nil && o.Channel.IsSet() {
		return true
	}

	return false
}

// SetChannel gets a reference to the given NullableString and assigns it to the Channel field.
func (o *RequestsLinkAnalyticTags) SetChannel(v string) {
	o.Channel.Set(&v)
}
// SetChannelNil sets the value for Channel to be an explicit nil
func (o *RequestsLinkAnalyticTags) SetChannelNil() {
	o.Channel.Set(nil)
}

// UnsetChannel ensures that no value is present for Channel, not even an explicit nil
func (o *RequestsLinkAnalyticTags) UnsetChannel() {
	o.Channel.Unset()
}

// GetFeature returns the Feature field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RequestsLinkAnalyticTags) GetFeature() string {
	if o == nil || IsNil(o.Feature.Get()) {
		var ret string
		return ret
	}
	return *o.Feature.Get()
}

// GetFeatureOk returns a tuple with the Feature field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RequestsLinkAnalyticTags) GetFeatureOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Feature.Get(), o.Feature.IsSet()
}

// HasFeature returns a boolean if a field has been set.
func (o *RequestsLinkAnalyticTags) HasFeature() bool {
	if o != nil && o.Feature.IsSet() {
		return true
	}

	return false
}

// SetFeature gets a reference to the given NullableString and assigns it to the Feature field.
func (o *RequestsLinkAnalyticTags) SetFeature(v string) {
	o.Feature.Set(&v)
}
// SetFeatureNil sets the value for Feature to be an explicit nil
func (o *RequestsLinkAnalyticTags) SetFeatureNil() {
	o.Feature.Set(nil)
}

// UnsetFeature ensures that no value is present for Feature, not even an explicit nil
func (o *RequestsLinkAnalyticTags) UnsetFeature() {
	o.Feature.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RequestsLinkAnalyticTags) GetTags() string {
	if o == nil || IsNil(o.Tags.Get()) {
		var ret string
		return ret
	}
	return *o.Tags.Get()
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RequestsLinkAnalyticTags) GetTagsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tags.Get(), o.Tags.IsSet()
}

// HasTags returns a boolean if a field has been set.
func (o *RequestsLinkAnalyticTags) HasTags() bool {
	if o != nil && o.Tags.IsSet() {
		return true
	}

	return false
}

// SetTags gets a reference to the given NullableString and assigns it to the Tags field.
func (o *RequestsLinkAnalyticTags) SetTags(v string) {
	o.Tags.Set(&v)
}
// SetTagsNil sets the value for Tags to be an explicit nil
func (o *RequestsLinkAnalyticTags) SetTagsNil() {
	o.Tags.Set(nil)
}

// UnsetTags ensures that no value is present for Tags, not even an explicit nil
func (o *RequestsLinkAnalyticTags) UnsetTags() {
	o.Tags.Unset()
}

func (o RequestsLinkAnalyticTags) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestsLinkAnalyticTags) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Campaign.IsSet() {
		toSerialize["campaign"] = o.Campaign.Get()
	}
	if o.Channel.IsSet() {
		toSerialize["channel"] = o.Channel.Get()
	}
	if o.Feature.IsSet() {
		toSerialize["feature"] = o.Feature.Get()
	}
	if o.Tags.IsSet() {
		toSerialize["tags"] = o.Tags.Get()
	}
	return toSerialize, nil
}

type NullableRequestsLinkAnalyticTags struct {
	value *RequestsLinkAnalyticTags
	isSet bool
}

func (v NullableRequestsLinkAnalyticTags) Get() *RequestsLinkAnalyticTags {
	return v.value
}

func (v *NullableRequestsLinkAnalyticTags) Set(val *RequestsLinkAnalyticTags) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestsLinkAnalyticTags) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestsLinkAnalyticTags) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestsLinkAnalyticTags(val *RequestsLinkAnalyticTags) *NullableRequestsLinkAnalyticTags {
	return &NullableRequestsLinkAnalyticTags{value: val, isSet: true}
}

func (v NullableRequestsLinkAnalyticTags) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestsLinkAnalyticTags) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


