/*
Polar Backend SDK Server

Backend SDK API for polar

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polar

import (
	"encoding/json"
)

// checks if the BeSdkRunEmailCampaignRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BeSdkRunEmailCampaignRequest{}

// BeSdkRunEmailCampaignRequest struct for BeSdkRunEmailCampaignRequest
type BeSdkRunEmailCampaignRequest struct {
	CampaignUnid string `json:"campaignUnid"`
}

// NewBeSdkRunEmailCampaignRequest instantiates a new BeSdkRunEmailCampaignRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBeSdkRunEmailCampaignRequest(campaignUnid string) *BeSdkRunEmailCampaignRequest {
	this := BeSdkRunEmailCampaignRequest{}
	this.CampaignUnid = campaignUnid
	return &this
}

// NewBeSdkRunEmailCampaignRequestWithDefaults instantiates a new BeSdkRunEmailCampaignRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBeSdkRunEmailCampaignRequestWithDefaults() *BeSdkRunEmailCampaignRequest {
	this := BeSdkRunEmailCampaignRequest{}
	return &this
}

// GetCampaignUnid returns the CampaignUnid field value
func (o *BeSdkRunEmailCampaignRequest) GetCampaignUnid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CampaignUnid
}

// GetCampaignUnidOk returns a tuple with the CampaignUnid field value
// and a boolean to check if the value has been set.
func (o *BeSdkRunEmailCampaignRequest) GetCampaignUnidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CampaignUnid, true
}

// SetCampaignUnid sets field value
func (o *BeSdkRunEmailCampaignRequest) SetCampaignUnid(v string) {
	o.CampaignUnid = v
}

func (o BeSdkRunEmailCampaignRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BeSdkRunEmailCampaignRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["campaignUnid"] = o.CampaignUnid
	return toSerialize, nil
}

type NullableBeSdkRunEmailCampaignRequest struct {
	value *BeSdkRunEmailCampaignRequest
	isSet bool
}

func (v NullableBeSdkRunEmailCampaignRequest) Get() *BeSdkRunEmailCampaignRequest {
	return v.value
}

func (v *NullableBeSdkRunEmailCampaignRequest) Set(val *BeSdkRunEmailCampaignRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBeSdkRunEmailCampaignRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBeSdkRunEmailCampaignRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBeSdkRunEmailCampaignRequest(val *BeSdkRunEmailCampaignRequest) *NullableBeSdkRunEmailCampaignRequest {
	return &NullableBeSdkRunEmailCampaignRequest{value: val, isSet: true}
}

func (v NullableBeSdkRunEmailCampaignRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBeSdkRunEmailCampaignRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


