/*
Polar Backend SDK Server

Backend SDK API for polar

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkattribution

import (
	"encoding/json"
)

// checks if the ResponsesSdkLinkResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesSdkLinkResponse{}

// ResponsesSdkLinkResponse struct for ResponsesSdkLinkResponse
type ResponsesSdkLinkResponse struct {
	Data *ResponsesSdkLinkResponseData `json:"data,omitempty"`
	RequestID *string `json:"requestID,omitempty"`
	Version *string `json:"version,omitempty"`
}

// NewResponsesSdkLinkResponse instantiates a new ResponsesSdkLinkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesSdkLinkResponse() *ResponsesSdkLinkResponse {
	this := ResponsesSdkLinkResponse{}
	return &this
}

// NewResponsesSdkLinkResponseWithDefaults instantiates a new ResponsesSdkLinkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesSdkLinkResponseWithDefaults() *ResponsesSdkLinkResponse {
	this := ResponsesSdkLinkResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ResponsesSdkLinkResponse) GetData() ResponsesSdkLinkResponseData {
	if o == nil || IsNil(o.Data) {
		var ret ResponsesSdkLinkResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesSdkLinkResponse) GetDataOk() (*ResponsesSdkLinkResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ResponsesSdkLinkResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ResponsesSdkLinkResponseData and assigns it to the Data field.
func (o *ResponsesSdkLinkResponse) SetData(v ResponsesSdkLinkResponseData) {
	o.Data = &v
}

// GetRequestID returns the RequestID field value if set, zero value otherwise.
func (o *ResponsesSdkLinkResponse) GetRequestID() string {
	if o == nil || IsNil(o.RequestID) {
		var ret string
		return ret
	}
	return *o.RequestID
}

// GetRequestIDOk returns a tuple with the RequestID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesSdkLinkResponse) GetRequestIDOk() (*string, bool) {
	if o == nil || IsNil(o.RequestID) {
		return nil, false
	}
	return o.RequestID, true
}

// HasRequestID returns a boolean if a field has been set.
func (o *ResponsesSdkLinkResponse) HasRequestID() bool {
	if o != nil && !IsNil(o.RequestID) {
		return true
	}

	return false
}

// SetRequestID gets a reference to the given string and assigns it to the RequestID field.
func (o *ResponsesSdkLinkResponse) SetRequestID(v string) {
	o.RequestID = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ResponsesSdkLinkResponse) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesSdkLinkResponse) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ResponsesSdkLinkResponse) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ResponsesSdkLinkResponse) SetVersion(v string) {
	o.Version = &v
}

func (o ResponsesSdkLinkResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesSdkLinkResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.RequestID) {
		toSerialize["requestID"] = o.RequestID
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableResponsesSdkLinkResponse struct {
	value *ResponsesSdkLinkResponse
	isSet bool
}

func (v NullableResponsesSdkLinkResponse) Get() *ResponsesSdkLinkResponse {
	return v.value
}

func (v *NullableResponsesSdkLinkResponse) Set(val *ResponsesSdkLinkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesSdkLinkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesSdkLinkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesSdkLinkResponse(val *ResponsesSdkLinkResponse) *NullableResponsesSdkLinkResponse {
	return &NullableResponsesSdkLinkResponse{value: val, isSet: true}
}

func (v NullableResponsesSdkLinkResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesSdkLinkResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


