/*
Polar Backend SDK Server

Backend SDK API for polar

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkattribution

import (
	"encoding/json"
)

// checks if the BeSdkCreateLinkRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BeSdkCreateLinkRequest{}

// BeSdkCreateLinkRequest struct for BeSdkCreateLinkRequest
type BeSdkCreateLinkRequest struct {
	AnalyticsTags *RequestsLinkAnalyticTags `json:"analyticsTags,omitempty"`
	Data map[string]interface{} `json:"data,omitempty"`
	Name string `json:"name"`
	Redirects *RequestsLinkRedirects `json:"redirects,omitempty"`
	SocialMediaTags *RequestsLinkSocialMediaTags `json:"socialMediaTags,omitempty"`
}

// NewBeSdkCreateLinkRequest instantiates a new BeSdkCreateLinkRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBeSdkCreateLinkRequest(name string) *BeSdkCreateLinkRequest {
	this := BeSdkCreateLinkRequest{}
	this.Name = name
	return &this
}

// NewBeSdkCreateLinkRequestWithDefaults instantiates a new BeSdkCreateLinkRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBeSdkCreateLinkRequestWithDefaults() *BeSdkCreateLinkRequest {
	this := BeSdkCreateLinkRequest{}
	return &this
}

// GetAnalyticsTags returns the AnalyticsTags field value if set, zero value otherwise.
func (o *BeSdkCreateLinkRequest) GetAnalyticsTags() RequestsLinkAnalyticTags {
	if o == nil || IsNil(o.AnalyticsTags) {
		var ret RequestsLinkAnalyticTags
		return ret
	}
	return *o.AnalyticsTags
}

// GetAnalyticsTagsOk returns a tuple with the AnalyticsTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BeSdkCreateLinkRequest) GetAnalyticsTagsOk() (*RequestsLinkAnalyticTags, bool) {
	if o == nil || IsNil(o.AnalyticsTags) {
		return nil, false
	}
	return o.AnalyticsTags, true
}

// HasAnalyticsTags returns a boolean if a field has been set.
func (o *BeSdkCreateLinkRequest) HasAnalyticsTags() bool {
	if o != nil && !IsNil(o.AnalyticsTags) {
		return true
	}

	return false
}

// SetAnalyticsTags gets a reference to the given RequestsLinkAnalyticTags and assigns it to the AnalyticsTags field.
func (o *BeSdkCreateLinkRequest) SetAnalyticsTags(v RequestsLinkAnalyticTags) {
	o.AnalyticsTags = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *BeSdkCreateLinkRequest) GetData() map[string]interface{} {
	if o == nil || IsNil(o.Data) {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BeSdkCreateLinkRequest) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Data) {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *BeSdkCreateLinkRequest) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *BeSdkCreateLinkRequest) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetName returns the Name field value
func (o *BeSdkCreateLinkRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BeSdkCreateLinkRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BeSdkCreateLinkRequest) SetName(v string) {
	o.Name = v
}

// GetRedirects returns the Redirects field value if set, zero value otherwise.
func (o *BeSdkCreateLinkRequest) GetRedirects() RequestsLinkRedirects {
	if o == nil || IsNil(o.Redirects) {
		var ret RequestsLinkRedirects
		return ret
	}
	return *o.Redirects
}

// GetRedirectsOk returns a tuple with the Redirects field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BeSdkCreateLinkRequest) GetRedirectsOk() (*RequestsLinkRedirects, bool) {
	if o == nil || IsNil(o.Redirects) {
		return nil, false
	}
	return o.Redirects, true
}

// HasRedirects returns a boolean if a field has been set.
func (o *BeSdkCreateLinkRequest) HasRedirects() bool {
	if o != nil && !IsNil(o.Redirects) {
		return true
	}

	return false
}

// SetRedirects gets a reference to the given RequestsLinkRedirects and assigns it to the Redirects field.
func (o *BeSdkCreateLinkRequest) SetRedirects(v RequestsLinkRedirects) {
	o.Redirects = &v
}

// GetSocialMediaTags returns the SocialMediaTags field value if set, zero value otherwise.
func (o *BeSdkCreateLinkRequest) GetSocialMediaTags() RequestsLinkSocialMediaTags {
	if o == nil || IsNil(o.SocialMediaTags) {
		var ret RequestsLinkSocialMediaTags
		return ret
	}
	return *o.SocialMediaTags
}

// GetSocialMediaTagsOk returns a tuple with the SocialMediaTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BeSdkCreateLinkRequest) GetSocialMediaTagsOk() (*RequestsLinkSocialMediaTags, bool) {
	if o == nil || IsNil(o.SocialMediaTags) {
		return nil, false
	}
	return o.SocialMediaTags, true
}

// HasSocialMediaTags returns a boolean if a field has been set.
func (o *BeSdkCreateLinkRequest) HasSocialMediaTags() bool {
	if o != nil && !IsNil(o.SocialMediaTags) {
		return true
	}

	return false
}

// SetSocialMediaTags gets a reference to the given RequestsLinkSocialMediaTags and assigns it to the SocialMediaTags field.
func (o *BeSdkCreateLinkRequest) SetSocialMediaTags(v RequestsLinkSocialMediaTags) {
	o.SocialMediaTags = &v
}

func (o BeSdkCreateLinkRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BeSdkCreateLinkRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AnalyticsTags) {
		toSerialize["analyticsTags"] = o.AnalyticsTags
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Redirects) {
		toSerialize["redirects"] = o.Redirects
	}
	if !IsNil(o.SocialMediaTags) {
		toSerialize["socialMediaTags"] = o.SocialMediaTags
	}
	return toSerialize, nil
}

type NullableBeSdkCreateLinkRequest struct {
	value *BeSdkCreateLinkRequest
	isSet bool
}

func (v NullableBeSdkCreateLinkRequest) Get() *BeSdkCreateLinkRequest {
	return v.value
}

func (v *NullableBeSdkCreateLinkRequest) Set(val *BeSdkCreateLinkRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBeSdkCreateLinkRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBeSdkCreateLinkRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBeSdkCreateLinkRequest(val *BeSdkCreateLinkRequest) *NullableBeSdkCreateLinkRequest {
	return &NullableBeSdkCreateLinkRequest{value: val, isSet: true}
}

func (v NullableBeSdkCreateLinkRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBeSdkCreateLinkRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


