/*
Polar Backend SDK Server

Backend SDK API for polar

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polar

import (
	"encoding/json"
)

// checks if the ResponsesSuccessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesSuccessResponse{}

// ResponsesSuccessResponse struct for ResponsesSuccessResponse
type ResponsesSuccessResponse struct {
	RequestID *string `json:"requestID,omitempty"`
	Version *string `json:"version,omitempty"`
}

// NewResponsesSuccessResponse instantiates a new ResponsesSuccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesSuccessResponse() *ResponsesSuccessResponse {
	this := ResponsesSuccessResponse{}
	return &this
}

// NewResponsesSuccessResponseWithDefaults instantiates a new ResponsesSuccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesSuccessResponseWithDefaults() *ResponsesSuccessResponse {
	this := ResponsesSuccessResponse{}
	return &this
}

// GetRequestID returns the RequestID field value if set, zero value otherwise.
func (o *ResponsesSuccessResponse) GetRequestID() string {
	if o == nil || IsNil(o.RequestID) {
		var ret string
		return ret
	}
	return *o.RequestID
}

// GetRequestIDOk returns a tuple with the RequestID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesSuccessResponse) GetRequestIDOk() (*string, bool) {
	if o == nil || IsNil(o.RequestID) {
		return nil, false
	}
	return o.RequestID, true
}

// HasRequestID returns a boolean if a field has been set.
func (o *ResponsesSuccessResponse) HasRequestID() bool {
	if o != nil && !IsNil(o.RequestID) {
		return true
	}

	return false
}

// SetRequestID gets a reference to the given string and assigns it to the RequestID field.
func (o *ResponsesSuccessResponse) SetRequestID(v string) {
	o.RequestID = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ResponsesSuccessResponse) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesSuccessResponse) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ResponsesSuccessResponse) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ResponsesSuccessResponse) SetVersion(v string) {
	o.Version = &v
}

func (o ResponsesSuccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesSuccessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RequestID) {
		toSerialize["requestID"] = o.RequestID
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableResponsesSuccessResponse struct {
	value *ResponsesSuccessResponse
	isSet bool
}

func (v NullableResponsesSuccessResponse) Get() *ResponsesSuccessResponse {
	return v.value
}

func (v *NullableResponsesSuccessResponse) Set(val *ResponsesSuccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesSuccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesSuccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesSuccessResponse(val *ResponsesSuccessResponse) *NullableResponsesSuccessResponse {
	return &NullableResponsesSuccessResponse{value: val, isSet: true}
}

func (v NullableResponsesSuccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesSuccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


