/*
Polar Backend SDK Server

Backend SDK API for polar

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polar

import (
	"encoding/json"
)

// checks if the ResponsesErrorDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesErrorDetails{}

// ResponsesErrorDetails struct for ResponsesErrorDetails
type ResponsesErrorDetails struct {
	Code *string `json:"code,omitempty"`
	Details interface{} `json:"details,omitempty"`
	Message *string `json:"message,omitempty"`
	StatusCode *int32 `json:"statusCode,omitempty"`
}

// NewResponsesErrorDetails instantiates a new ResponsesErrorDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesErrorDetails() *ResponsesErrorDetails {
	this := ResponsesErrorDetails{}
	return &this
}

// NewResponsesErrorDetailsWithDefaults instantiates a new ResponsesErrorDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesErrorDetailsWithDefaults() *ResponsesErrorDetails {
	this := ResponsesErrorDetails{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *ResponsesErrorDetails) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesErrorDetails) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *ResponsesErrorDetails) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *ResponsesErrorDetails) SetCode(v string) {
	o.Code = &v
}

// GetDetails returns the Details field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResponsesErrorDetails) GetDetails() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponsesErrorDetails) GetDetailsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Details) {
		return nil, false
	}
	return &o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *ResponsesErrorDetails) HasDetails() bool {
	if o != nil && IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given interface{} and assigns it to the Details field.
func (o *ResponsesErrorDetails) SetDetails(v interface{}) {
	o.Details = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ResponsesErrorDetails) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesErrorDetails) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ResponsesErrorDetails) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ResponsesErrorDetails) SetMessage(v string) {
	o.Message = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *ResponsesErrorDetails) GetStatusCode() int32 {
	if o == nil || IsNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesErrorDetails) GetStatusCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.StatusCode) {
		return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *ResponsesErrorDetails) HasStatusCode() bool {
	if o != nil && !IsNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *ResponsesErrorDetails) SetStatusCode(v int32) {
	o.StatusCode = &v
}

func (o ResponsesErrorDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesErrorDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if o.Details != nil {
		toSerialize["details"] = o.Details
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.StatusCode) {
		toSerialize["statusCode"] = o.StatusCode
	}
	return toSerialize, nil
}

type NullableResponsesErrorDetails struct {
	value *ResponsesErrorDetails
	isSet bool
}

func (v NullableResponsesErrorDetails) Get() *ResponsesErrorDetails {
	return v.value
}

func (v *NullableResponsesErrorDetails) Set(val *ResponsesErrorDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesErrorDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesErrorDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesErrorDetails(val *ResponsesErrorDetails) *NullableResponsesErrorDetails {
	return &NullableResponsesErrorDetails{value: val, isSet: true}
}

func (v NullableResponsesErrorDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesErrorDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


