/*
Polar Backend SDK Server

Backend SDK API for polar

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkattribution

import (
	"encoding/json"
)

// checks if the RequestsLinkSocialMediaTags type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestsLinkSocialMediaTags{}

// RequestsLinkSocialMediaTags struct for RequestsLinkSocialMediaTags
type RequestsLinkSocialMediaTags struct {
	Description string `json:"description"`
	Title string `json:"title"`
}

// NewRequestsLinkSocialMediaTags instantiates a new RequestsLinkSocialMediaTags object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestsLinkSocialMediaTags(description string, title string) *RequestsLinkSocialMediaTags {
	this := RequestsLinkSocialMediaTags{}
	this.Description = description
	this.Title = title
	return &this
}

// NewRequestsLinkSocialMediaTagsWithDefaults instantiates a new RequestsLinkSocialMediaTags object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestsLinkSocialMediaTagsWithDefaults() *RequestsLinkSocialMediaTags {
	this := RequestsLinkSocialMediaTags{}
	return &this
}

// GetDescription returns the Description field value
func (o *RequestsLinkSocialMediaTags) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *RequestsLinkSocialMediaTags) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *RequestsLinkSocialMediaTags) SetDescription(v string) {
	o.Description = v
}

// GetTitle returns the Title field value
func (o *RequestsLinkSocialMediaTags) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *RequestsLinkSocialMediaTags) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *RequestsLinkSocialMediaTags) SetTitle(v string) {
	o.Title = v
}

func (o RequestsLinkSocialMediaTags) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestsLinkSocialMediaTags) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["title"] = o.Title
	return toSerialize, nil
}

type NullableRequestsLinkSocialMediaTags struct {
	value *RequestsLinkSocialMediaTags
	isSet bool
}

func (v NullableRequestsLinkSocialMediaTags) Get() *RequestsLinkSocialMediaTags {
	return v.value
}

func (v *NullableRequestsLinkSocialMediaTags) Set(val *RequestsLinkSocialMediaTags) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestsLinkSocialMediaTags) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestsLinkSocialMediaTags) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestsLinkSocialMediaTags(val *RequestsLinkSocialMediaTags) *NullableRequestsLinkSocialMediaTags {
	return &NullableRequestsLinkSocialMediaTags{value: val, isSet: true}
}

func (v NullableRequestsLinkSocialMediaTags) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestsLinkSocialMediaTags) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


