/*
Polar Backend SDK Server

Backend SDK API for polar

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polar

import (
	"encoding/json"
)

// checks if the ResponsesLinkSocialMediaTags type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesLinkSocialMediaTags{}

// ResponsesLinkSocialMediaTags struct for ResponsesLinkSocialMediaTags
type ResponsesLinkSocialMediaTags struct {
	Description string `json:"description"`
	Title string `json:"title"`
}

// NewResponsesLinkSocialMediaTags instantiates a new ResponsesLinkSocialMediaTags object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesLinkSocialMediaTags(description string, title string) *ResponsesLinkSocialMediaTags {
	this := ResponsesLinkSocialMediaTags{}
	this.Description = description
	this.Title = title
	return &this
}

// NewResponsesLinkSocialMediaTagsWithDefaults instantiates a new ResponsesLinkSocialMediaTags object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesLinkSocialMediaTagsWithDefaults() *ResponsesLinkSocialMediaTags {
	this := ResponsesLinkSocialMediaTags{}
	return &this
}

// GetDescription returns the Description field value
func (o *ResponsesLinkSocialMediaTags) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ResponsesLinkSocialMediaTags) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ResponsesLinkSocialMediaTags) SetDescription(v string) {
	o.Description = v
}

// GetTitle returns the Title field value
func (o *ResponsesLinkSocialMediaTags) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ResponsesLinkSocialMediaTags) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ResponsesLinkSocialMediaTags) SetTitle(v string) {
	o.Title = v
}

func (o ResponsesLinkSocialMediaTags) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesLinkSocialMediaTags) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["description"] = o.Description
	toSerialize["title"] = o.Title
	return toSerialize, nil
}

type NullableResponsesLinkSocialMediaTags struct {
	value *ResponsesLinkSocialMediaTags
	isSet bool
}

func (v NullableResponsesLinkSocialMediaTags) Get() *ResponsesLinkSocialMediaTags {
	return v.value
}

func (v *NullableResponsesLinkSocialMediaTags) Set(val *ResponsesLinkSocialMediaTags) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesLinkSocialMediaTags) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesLinkSocialMediaTags) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesLinkSocialMediaTags(val *ResponsesLinkSocialMediaTags) *NullableResponsesLinkSocialMediaTags {
	return &NullableResponsesLinkSocialMediaTags{value: val, isSet: true}
}

func (v NullableResponsesLinkSocialMediaTags) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesLinkSocialMediaTags) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


