/*
Polar Backend SDK Server

Backend SDK API for polar

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polar

import (
	"encoding/json"
)

// checks if the BeSdkUserProfileUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BeSdkUserProfileUpdateRequest{}

// BeSdkUserProfileUpdateRequest struct for BeSdkUserProfileUpdateRequest
type BeSdkUserProfileUpdateRequest struct {
	ClobberMatchingAttributes *bool `json:"clobberMatchingAttributes,omitempty"`
	Data map[string]interface{} `json:"data"`
	UserID *string `json:"userID,omitempty"`
}

// NewBeSdkUserProfileUpdateRequest instantiates a new BeSdkUserProfileUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBeSdkUserProfileUpdateRequest(data map[string]interface{}) *BeSdkUserProfileUpdateRequest {
	this := BeSdkUserProfileUpdateRequest{}
	this.Data = data
	return &this
}

// NewBeSdkUserProfileUpdateRequestWithDefaults instantiates a new BeSdkUserProfileUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBeSdkUserProfileUpdateRequestWithDefaults() *BeSdkUserProfileUpdateRequest {
	this := BeSdkUserProfileUpdateRequest{}
	return &this
}

// GetClobberMatchingAttributes returns the ClobberMatchingAttributes field value if set, zero value otherwise.
func (o *BeSdkUserProfileUpdateRequest) GetClobberMatchingAttributes() bool {
	if o == nil || IsNil(o.ClobberMatchingAttributes) {
		var ret bool
		return ret
	}
	return *o.ClobberMatchingAttributes
}

// GetClobberMatchingAttributesOk returns a tuple with the ClobberMatchingAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BeSdkUserProfileUpdateRequest) GetClobberMatchingAttributesOk() (*bool, bool) {
	if o == nil || IsNil(o.ClobberMatchingAttributes) {
		return nil, false
	}
	return o.ClobberMatchingAttributes, true
}

// HasClobberMatchingAttributes returns a boolean if a field has been set.
func (o *BeSdkUserProfileUpdateRequest) HasClobberMatchingAttributes() bool {
	if o != nil && !IsNil(o.ClobberMatchingAttributes) {
		return true
	}

	return false
}

// SetClobberMatchingAttributes gets a reference to the given bool and assigns it to the ClobberMatchingAttributes field.
func (o *BeSdkUserProfileUpdateRequest) SetClobberMatchingAttributes(v bool) {
	o.ClobberMatchingAttributes = &v
}

// GetData returns the Data field value
func (o *BeSdkUserProfileUpdateRequest) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BeSdkUserProfileUpdateRequest) GetDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *BeSdkUserProfileUpdateRequest) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetUserID returns the UserID field value if set, zero value otherwise.
func (o *BeSdkUserProfileUpdateRequest) GetUserID() string {
	if o == nil || IsNil(o.UserID) {
		var ret string
		return ret
	}
	return *o.UserID
}

// GetUserIDOk returns a tuple with the UserID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BeSdkUserProfileUpdateRequest) GetUserIDOk() (*string, bool) {
	if o == nil || IsNil(o.UserID) {
		return nil, false
	}
	return o.UserID, true
}

// HasUserID returns a boolean if a field has been set.
func (o *BeSdkUserProfileUpdateRequest) HasUserID() bool {
	if o != nil && !IsNil(o.UserID) {
		return true
	}

	return false
}

// SetUserID gets a reference to the given string and assigns it to the UserID field.
func (o *BeSdkUserProfileUpdateRequest) SetUserID(v string) {
	o.UserID = &v
}

func (o BeSdkUserProfileUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BeSdkUserProfileUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClobberMatchingAttributes) {
		toSerialize["clobberMatchingAttributes"] = o.ClobberMatchingAttributes
	}
	toSerialize["data"] = o.Data
	if !IsNil(o.UserID) {
		toSerialize["userID"] = o.UserID
	}
	return toSerialize, nil
}

type NullableBeSdkUserProfileUpdateRequest struct {
	value *BeSdkUserProfileUpdateRequest
	isSet bool
}

func (v NullableBeSdkUserProfileUpdateRequest) Get() *BeSdkUserProfileUpdateRequest {
	return v.value
}

func (v *NullableBeSdkUserProfileUpdateRequest) Set(val *BeSdkUserProfileUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBeSdkUserProfileUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBeSdkUserProfileUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBeSdkUserProfileUpdateRequest(val *BeSdkUserProfileUpdateRequest) *NullableBeSdkUserProfileUpdateRequest {
	return &NullableBeSdkUserProfileUpdateRequest{value: val, isSet: true}
}

func (v NullableBeSdkUserProfileUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBeSdkUserProfileUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


