/*
Polar Backend SDK Server

Backend SDK API for polar

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package linkattribution

import (
	"encoding/json"
)

// checks if the ResponsesErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesErrorResponse{}

// ResponsesErrorResponse struct for ResponsesErrorResponse
type ResponsesErrorResponse struct {
	Error *ResponsesErrorDetails `json:"error,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
	Version *string `json:"version,omitempty"`
}

// NewResponsesErrorResponse instantiates a new ResponsesErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesErrorResponse() *ResponsesErrorResponse {
	this := ResponsesErrorResponse{}
	return &this
}

// NewResponsesErrorResponseWithDefaults instantiates a new ResponsesErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesErrorResponseWithDefaults() *ResponsesErrorResponse {
	this := ResponsesErrorResponse{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *ResponsesErrorResponse) GetError() ResponsesErrorDetails {
	if o == nil || IsNil(o.Error) {
		var ret ResponsesErrorDetails
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesErrorResponse) GetErrorOk() (*ResponsesErrorDetails, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *ResponsesErrorResponse) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given ResponsesErrorDetails and assigns it to the Error field.
func (o *ResponsesErrorResponse) SetError(v ResponsesErrorDetails) {
	o.Error = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *ResponsesErrorResponse) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesErrorResponse) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *ResponsesErrorResponse) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *ResponsesErrorResponse) SetRequestId(v string) {
	o.RequestId = &v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *ResponsesErrorResponse) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesErrorResponse) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *ResponsesErrorResponse) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *ResponsesErrorResponse) SetVersion(v string) {
	o.Version = &v
}

func (o ResponsesErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	return toSerialize, nil
}

type NullableResponsesErrorResponse struct {
	value *ResponsesErrorResponse
	isSet bool
}

func (v NullableResponsesErrorResponse) Get() *ResponsesErrorResponse {
	return v.value
}

func (v *NullableResponsesErrorResponse) Set(val *ResponsesErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesErrorResponse(val *ResponsesErrorResponse) *NullableResponsesErrorResponse {
	return &NullableResponsesErrorResponse{value: val, isSet: true}
}

func (v NullableResponsesErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


