/*
Polar Backend SDK Server

Backend SDK API for polar

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package polar

import (
	"encoding/json"
)

// checks if the BeSdkRunPushCampaignRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BeSdkRunPushCampaignRequest{}

// BeSdkRunPushCampaignRequest struct for BeSdkRunPushCampaignRequest
type BeSdkRunPushCampaignRequest struct {
	CampaignUnid string `json:"campaignUnid"`
	CustomData map[string]interface{} `json:"customData,omitempty"`
	UserUnid string `json:"userUnid"`
}

// NewBeSdkRunPushCampaignRequest instantiates a new BeSdkRunPushCampaignRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBeSdkRunPushCampaignRequest(campaignUnid string, userUnid string) *BeSdkRunPushCampaignRequest {
	this := BeSdkRunPushCampaignRequest{}
	this.CampaignUnid = campaignUnid
	this.UserUnid = userUnid
	return &this
}

// NewBeSdkRunPushCampaignRequestWithDefaults instantiates a new BeSdkRunPushCampaignRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBeSdkRunPushCampaignRequestWithDefaults() *BeSdkRunPushCampaignRequest {
	this := BeSdkRunPushCampaignRequest{}
	return &this
}

// GetCampaignUnid returns the CampaignUnid field value
func (o *BeSdkRunPushCampaignRequest) GetCampaignUnid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CampaignUnid
}

// GetCampaignUnidOk returns a tuple with the CampaignUnid field value
// and a boolean to check if the value has been set.
func (o *BeSdkRunPushCampaignRequest) GetCampaignUnidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CampaignUnid, true
}

// SetCampaignUnid sets field value
func (o *BeSdkRunPushCampaignRequest) SetCampaignUnid(v string) {
	o.CampaignUnid = v
}

// GetCustomData returns the CustomData field value if set, zero value otherwise.
func (o *BeSdkRunPushCampaignRequest) GetCustomData() map[string]interface{} {
	if o == nil || IsNil(o.CustomData) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomData
}

// GetCustomDataOk returns a tuple with the CustomData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BeSdkRunPushCampaignRequest) GetCustomDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomData) {
		return map[string]interface{}{}, false
	}
	return o.CustomData, true
}

// HasCustomData returns a boolean if a field has been set.
func (o *BeSdkRunPushCampaignRequest) HasCustomData() bool {
	if o != nil && !IsNil(o.CustomData) {
		return true
	}

	return false
}

// SetCustomData gets a reference to the given map[string]interface{} and assigns it to the CustomData field.
func (o *BeSdkRunPushCampaignRequest) SetCustomData(v map[string]interface{}) {
	o.CustomData = v
}

// GetUserUnid returns the UserUnid field value
func (o *BeSdkRunPushCampaignRequest) GetUserUnid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserUnid
}

// GetUserUnidOk returns a tuple with the UserUnid field value
// and a boolean to check if the value has been set.
func (o *BeSdkRunPushCampaignRequest) GetUserUnidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserUnid, true
}

// SetUserUnid sets field value
func (o *BeSdkRunPushCampaignRequest) SetUserUnid(v string) {
	o.UserUnid = v
}

func (o BeSdkRunPushCampaignRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BeSdkRunPushCampaignRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["campaignUnid"] = o.CampaignUnid
	if !IsNil(o.CustomData) {
		toSerialize["customData"] = o.CustomData
	}
	toSerialize["userUnid"] = o.UserUnid
	return toSerialize, nil
}

type NullableBeSdkRunPushCampaignRequest struct {
	value *BeSdkRunPushCampaignRequest
	isSet bool
}

func (v NullableBeSdkRunPushCampaignRequest) Get() *BeSdkRunPushCampaignRequest {
	return v.value
}

func (v *NullableBeSdkRunPushCampaignRequest) Set(val *BeSdkRunPushCampaignRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBeSdkRunPushCampaignRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBeSdkRunPushCampaignRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBeSdkRunPushCampaignRequest(val *BeSdkRunPushCampaignRequest) *NullableBeSdkRunPushCampaignRequest {
	return &NullableBeSdkRunPushCampaignRequest{value: val, isSet: true}
}

func (v NullableBeSdkRunPushCampaignRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBeSdkRunPushCampaignRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


